---
title: "boat movement analysis"
author: "Tobias Schwoerer"
date: "November 21, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Importing the data files, visualizing all respondent boat tracks 

```{r}
library(jsonlite)
library(geojson)
library(leaflet)
library(dplyr)
library(geojsonio)

#cleaned up features (tracks the respondents entered into the mapping tool)
map <- geojson_read("D:/Dropbox/DATA/2018_boat_survey/map.geojson",what = "sp")
features <- read.csv("D:/Dropbox/DATA/2018_boat_survey/features.csv", stringsAsFactors = FALSE)

#cleaned data associated with the survey answers of each respondent
data <- read.csv("D:/Dropbox/DATA/2018_boat_survey/data.csv")


# the joined data and map output, joined these files using the python script
mapdata <- geojson_read("D:/Dropbox/DATA/2018_boat_survey/output.geojson",what = "sp")

#creating leaflet map showing all routes
leaflet(mapdata) %>%
  addTiles() %>%
  addPolylines() %>%
  addProviderTiles(providers$Stamen.TerrainBackground)
```


#High priority TASKS
1) need to convert the frequencies in numbers
2) can I visualize the frequencies? 
3) visualize out of state origin tracks



# Low priority tasks
3) Does a hex map make sense?

































# Integrating dynamic with static elements (Source: https://rstudio.github.io/leaflet/shiny.html)
```{r}
library(shiny)
library(leaflet)
library(RColorBrewer)

ui <- bootstrapPage(
  tags$style(type = "text/css", "html, body {width:100%;height:100%}"),
  leafletOutput("map", width = "100%", height = "100%"),
  absolutePanel(top = 10, right = 10,
    checkboxInput("select","Show tracks of",
      list(`boats operated outside Alaska before coming to Alaska` = list("NY", "NJ", "CT"),
           `boats Operated only in Alaska in 2018` = list(""),
           `all boats` = list("British Columbia","Washington","Kansas","Yukon Territories",""),
                selected = ""
           ),
      
        ),
    checkboxInput("legend", "Show legend", TRUE)
  )
)

```


```{r}
server <- function(input, output, session) {

  # Reactive expression for the data subsetted to what the user selected
  filteredData <- reactive({
    mapdata[mapdata$freshOutside =="Yes",]
  })

  # This reactive expression represents the palette function,
  # which changes as the user makes selections in UI.
  colorpal <- reactive({
    colorNumeric(input$colors, quakes$mag)
  })

  output$map <- renderLeaflet({
    # Use leaflet() here, and only include aspects of the map that
    # won't need to change dynamically (at least, not unless the
    # entire map is being torn down and recreated).
    leaflet(mapdata) %>% addTiles() %>%
      fitBounds(~min(long), ~min(lat), ~max(long), ~max(lat))
  })

  # Incremental changes to the map (in this case, replacing the
  # circles when a new color is chosen) should be performed in
  # an observer. Each independent set of things that can change
  # should be managed in its own observer.
  observe({
    pal <- colorpal()

    leafletProxy("map", data = filteredData()) %>%
      clearShapes() %>%
      addCircles(radius = ~10^mag/10, weight = 1, color = "#777777",
        fillColor = ~pal(mag), fillOpacity = 0.7, popup = ~paste(mag)
      )
  })

  # Use a separate observer to recreate the legend as needed.
  observe({
    proxy <- leafletProxy("map", data = quakes)

    # Remove any existing legend, and only if the legend is
    # enabled, create a new one.
    proxy %>% clearControls()
    if (input$legend) {
      pal <- colorpal()
      proxy %>% addLegend(position = "bottomright",
        pal = pal, values = ~mag
      )
    }
  })
}

shinyApp(ui, server)
 
``` 
 
```{r}
# write survey answers as geojson
geojson_write(answers, "data/answers.geojson")

#validating this file as a true json file
geojsonlint::geojson_lint("data/answers.geojson")

answersJson <- geojson_read("data/answers.geojson", what = "sp")

# combining json files
files <- c("routes", "answersJson")
jsonl <- lapply(files, function(f) fromJSON(file = f))
jsonc <- toJSON(jsonl)
write(jsonc, file = "jsonc")
class(jsonc)

#creating leaflet map
leaflet(data) %>%
  addTiles() %>%
  addPolylines() 
```

